# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
# relative_permalinks: true

# Setup
title:            IDEP Partners Toolkit
tagline:          'UCLA'
description:      'A guide to standards and workflows for IDEP partner institutions.'
url:              http://hyde.getpoole.com
baseurl:          /

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde

defaultlang:      eng

t:
  eng:
    title:        'IDEP Partners Toolkit'
    description:  'A guide to standards and workflows for IDEP partner institutions.'
  spa:
    title:        ''
    description:  'Una guía de estándares y flujos de trabajo para las instituciones asociadas al IDEP.'
  arm:
    title:        ''
    description:  'IDEP գործընկեր հաստատությունների համար ստանդարտների եւ աշխատանքի արդյունքի ուղեցույց:'
